# Generated by Django 3.1.4 on 2021-02-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0002_quote_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='height',
            field=models.PositiveIntegerField(default=0, help_text='CMs'),
        ),
        migrations.AddField(
            model_name='quote',
            name='lenght',
            field=models.PositiveIntegerField(default=0, help_text='CMs'),
        ),
        migrations.AddField(
            model_name='quote',
            name='width',
            field=models.PositiveIntegerField(default=0, help_text='CMs'),
        ),
    ]
