# Generated by Django 3.1.4 on 2021-02-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0003_auto_20210228_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='height',
            field=models.PositiveIntegerField(help_text='CMs'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='lenght',
            field=models.PositiveIntegerField(help_text='CMs'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='width',
            field=models.PositiveIntegerField(help_text='CMs'),
        ),
    ]
