# Generated by Django 3.1.4 on 2021-02-28 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0004_auto_20210228_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='lenght',
            new_name='length',
        ),
    ]
