# Generated by Django 3.1.4 on 2021-02-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0007_auto_20210228_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='collection',
            new_name='c_postcode',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='delivery',
            new_name='d_postcode',
        ),
        migrations.AlterField(
            model_name='quote',
            name='c_town_or_city',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='quote',
            name='d_town_or_city',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
