# Generated by Django 3.1.4 on 2021-03-01 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0011_auto_20210301_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text='KGs', max_digits=5),
        ),
    ]
