# Generated by Django 3.1.4 on 2021-03-03 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0012_auto_20210301_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='am_10',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='am_12',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='c_date',
            field=models.DateTimeField(blank=True, default='2012-09-04 06:00'),
        ),
        migrations.AddField(
            model_name='quote',
            name='d_date',
            field=models.DateTimeField(blank=True, default='2012-09-04 06:00'),
        ),
        migrations.AddField(
            model_name='quote',
            name='fragile',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='security',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
