# Generated by Django 3.1.4 on 2021-03-03 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0014_auto_20210303_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='c_date',
            field=models.DateField(default='2012-09-04', null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='d_date',
            field=models.DateField(default='2012-09-04', null=True),
        ),
    ]
