# Generated by Django 3.1.4 on 2021-03-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0015_auto_20210303_0113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='am_10',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='am_12',
        ),
        migrations.AddField(
            model_name='quote',
            name='service',
            field=models.CharField(default='NextDay', max_length=20),
        ),
    ]
