# Generated by Django 3.1.4 on 2021-03-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0016_auto_20210303_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='service',
            field=models.CharField(max_length=20),
        ),
    ]
