# Generated by Django 3.1.4 on 2021-03-03 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0023_auto_20210303_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='spec_service',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
