# Generated by Django 3.1.4 on 2021-03-03 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0024_auto_20210303_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='spec_service',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
