# Generated by Django 3.1.4 on 2021-03-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0026_auto_20210303_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='service',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
