# Generated by Django 3.1.4 on 2021-03-04 22:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0028_auto_20210303_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='c_postcode',
            field=models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator(inverse_match=False, message='Enter a Valid Postcode', regex='')], verbose_name='Collection Postcode'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='height',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='quote',
            name='length',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='quote',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text="Max 30kg's", max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='quote',
            name='width',
            field=models.PositiveIntegerField(),
        ),
    ]
