# Generated by Django 3.1.4 on 2021-03-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0029_auto_20210304_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='c_postcode',
            field=models.CharField(blank=True, max_length=8, verbose_name='Collection Postcode'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text="Max 30kg's", max_digits=5),
        ),
    ]
