# Generated by Django 3.1.4 on 2021-03-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0030_auto_20210306_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='c_postcode',
            field=models.CharField(max_length=8, verbose_name='Collection Postcode'),
        ),
    ]
