# Generated by Django 3.1.4 on 2021-03-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0037_auto_20210311_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='volume_weight1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='volume_weight2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='volume_weight3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='volume_weight4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
