# Generated by Django 3.1.4 on 2021-03-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0038_auto_20210311_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='volume_weight',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
