# Generated by Django 3.1.4 on 2021-03-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0042_auto_20210315_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='phone_number',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
    ]
