# Generated by Django 3.1.4 on 2021-03-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0043_auto_20210316_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='volume_weight1',
            field=models.CharField(blank=True, default=0, max_length=7, verbose_name='Volume Weight'),
        ),
    ]
