# Generated by Django 3.1.4 on 2021-03-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0045_auto_20210316_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='spec_service',
            field=models.CharField(max_length=20, verbose_name='Premium Service'),
        ),
    ]
