# Generated by Django 3.1.8 on 2021-04-26 18:11

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0046_auto_20210316_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_ref', models.CharField(editable=False, max_length=10)),
                ('d_postcode', models.CharField(max_length=8, verbose_name='Delivery Postcode')),
                ('c_postcode', models.CharField(max_length=8, verbose_name='Collection Postcode')),
                ('overall_weight', models.CharField(blank=True, default=0, max_length=7, verbose_name='Volume Weight')),
                ('overall_volume', models.CharField(blank=True, default=0, max_length=7, verbose_name='Volume Weight')),
                ('weight', models.DecimalField(decimal_places=2, help_text="Max 30kg's", max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=7)),
                ('width', models.DecimalField(decimal_places=2, max_digits=7)),
                ('length', models.DecimalField(decimal_places=2, max_digits=7)),
                ('volume_weight', models.CharField(blank=True, default=0, max_length=7, verbose_name='Volume Weight')),
                ('weight1', models.DecimalField(blank=True, decimal_places=2, default=0, help_text="Max 30kg's", max_digits=5, null=True, verbose_name='Weight')),
                ('height1', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Height')),
                ('width1', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Width')),
                ('length1', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Length')),
                ('volume_weight1', models.CharField(blank=True, default=0, max_length=7, verbose_name='Volume Weight')),
                ('weight2', models.DecimalField(blank=True, decimal_places=2, default=0, help_text="Max 30kg's", max_digits=5, null=True, verbose_name='Weight')),
                ('height2', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Height')),
                ('width2', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Width')),
                ('length2', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Length')),
                ('volume_weight2', models.CharField(blank=True, default=0, max_length=7, verbose_name='Volume Weight')),
                ('weight3', models.DecimalField(blank=True, decimal_places=2, default=0, help_text="Max 30kg's", max_digits=5, null=True, verbose_name='Weight')),
                ('height3', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Height')),
                ('width3', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Width')),
                ('length3', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Length')),
                ('volume_weight3', models.CharField(blank=True, default=0, max_length=7, verbose_name='Volume Weight')),
                ('weight4', models.DecimalField(blank=True, decimal_places=2, default=0, help_text="Max 30kg's", max_digits=5, null=True, verbose_name='Weight')),
                ('height4', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Height')),
                ('width4', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Width')),
                ('length4', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Length')),
                ('volume_weight4', models.CharField(blank=True, default=0, max_length=7, verbose_name='Volume Weight')),
                ('service', models.CharField(max_length=20)),
                ('spec_service', models.CharField(max_length=20, verbose_name='Premium Service')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('quote', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('bookers_email', models.EmailField(max_length=254)),
                ('bookers_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('d_contact_name', models.CharField(max_length=50)),
                ('d_company', models.CharField(blank=True, max_length=100)),
                ('d_email', models.EmailField(blank=True, max_length=254)),
                ('d_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('d_street_address1', models.CharField(max_length=80)),
                ('d_street_address2', models.CharField(blank=True, max_length=80)),
                ('d_town_or_city', models.CharField(max_length=40)),
                ('d_county', models.CharField(blank=True, max_length=80)),
                ('c_contact_name', models.CharField(max_length=50)),
                ('c_company', models.CharField(blank=True, max_length=100)),
                ('c_email', models.EmailField(blank=True, max_length=254)),
                ('c_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('c_street_address1', models.CharField(max_length=80)),
                ('c_street_address2', models.CharField(blank=True, max_length=80)),
                ('c_town_or_city', models.CharField(max_length=40)),
                ('c_county', models.CharField(blank=True, max_length=80)),
                ('date_booked', models.DateField(default=django.utils.timezone.now, null=True)),
                ('payment_complete', models.BooleanField(default=False, help_text='Only book once payment is complete!', verbose_name='Payment Complete')),
            ],
            options={
                'verbose_name_plural': 'Bookings',
            },
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='c_email',
            new_name='bookers_email',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='c_company',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='c_contact_name',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='c_county',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='c_date',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='c_phone_number',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='c_street_address1',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='c_street_address2',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='c_town_or_city',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='d_company',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='d_contact_name',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='d_county',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='d_date',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='d_email',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='d_phone_number',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='d_street_address1',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='d_street_address2',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='d_town_or_city',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='email',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='quote',
            name='bookers_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default=0, max_length=128, region=None),
            preserve_default=False,
        ),
    ]
