# Generated by Django 3.1.6 on 2021-03-23 23:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0046_auto_20210316_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='c_email',
            new_name='bookers_email',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='c_company',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='c_contact_name',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='c_county',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='c_date',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='c_phone_number',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='c_street_address1',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='c_street_address2',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='c_town_or_city',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='d_company',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='d_contact_name',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='d_county',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='d_date',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='d_email',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='d_phone_number',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='d_street_address1',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='d_street_address2',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='d_town_or_city',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='email',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='quote',
            name='bookers_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='tom@wilson-express.co.uk', max_length=128, region=None),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('quote_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quote.quote')),
                ('d_contact_name', models.CharField(max_length=50)),
                ('d_company', models.CharField(blank=True, max_length=100)),
                ('d_email', models.EmailField(max_length=254)),
                ('d_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('d_street_address1', models.CharField(max_length=80)),
                ('d_street_address2', models.CharField(blank=True, max_length=80)),
                ('d_town_or_city', models.CharField(blank=True, max_length=40)),
                ('d_county', models.CharField(blank=True, max_length=80)),
                ('c_contact_name', models.CharField(max_length=50)),
                ('c_company', models.CharField(blank=True, max_length=100)),
                ('c_email', models.EmailField(max_length=254)),
                ('c_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('c_street_address1', models.CharField(max_length=80)),
                ('c_street_address2', models.CharField(blank=True, max_length=80)),
                ('c_town_or_city', models.CharField(blank=True, max_length=40)),
                ('c_county', models.CharField(blank=True, max_length=80)),
                ('date_booked', models.DateField(default=datetime.datetime(2021, 3, 23, 23, 5, 47, 785297, tzinfo=utc), null=True)),
                ('booking_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference', to='quote.quote')),
            ],
            options={
                'verbose_name_plural': 'Bookings',
            },
            bases=('quote.quote', models.Model),
        ),
    ]
