# Generated by Django 3.1.6 on 2021-03-23 23:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0047_auto_20210323_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_booked',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
