# Generated by Django 3.1.8 on 2021-04-26 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0047_auto_20210426_1811'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='Bookings',
        ),
    ]
