# Generated by Django 3.1.6 on 2021-04-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0048_auto_20210323_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='c_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='booking',
            name='c_town_or_city',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='booking',
            name='d_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='booking',
            name='d_town_or_city',
            field=models.CharField(max_length=40),
        ),
    ]
