# Generated by Django 3.1.8 on 2021-04-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0048_auto_20210426_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='quote',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='bookings',
            name='overall_weight',
            field=models.CharField(blank=True, default=0, max_length=10, verbose_name='Actual Weight'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='overall_weight',
            field=models.CharField(blank=True, default=0, max_length=10, verbose_name='Actual Weight'),
        ),
    ]
