# Generated by Django 3.1.8 on 2021-04-28 22:37

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0049_auto_20210426_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='items',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookings',
            name='bookers_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Bookers Phone Number'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='c_company',
            field=models.CharField(blank=True, max_length=100, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='c_contact_name',
            field=models.CharField(max_length=50, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='c_county',
            field=models.CharField(blank=True, max_length=80, verbose_name='County'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='c_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='c_postcode',
            field=models.CharField(max_length=8, verbose_name='Postcode'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='c_street_address1',
            field=models.CharField(max_length=80, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='c_street_address2',
            field=models.CharField(blank=True, max_length=80, verbose_name='Address Line 2'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='c_town_or_city',
            field=models.CharField(max_length=40, verbose_name='Town or City'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='d_company',
            field=models.CharField(blank=True, max_length=100, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='d_contact_name',
            field=models.CharField(max_length=50, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='d_county',
            field=models.CharField(blank=True, max_length=80, verbose_name='County'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='d_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='d_postcode',
            field=models.CharField(max_length=8, verbose_name='Postcode'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='d_street_address1',
            field=models.CharField(max_length=80, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='d_street_address2',
            field=models.CharField(blank=True, max_length=80, verbose_name='Address Line 2'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='d_town_or_city',
            field=models.CharField(max_length=40, verbose_name='Town or City'),
        ),
    ]
