# Generated by Django 3.1.8 on 2021-04-28 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0051_quote_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='items',
            field=models.IntegerField(default=0),
        ),
    ]
