# Generated by Django 3.1.8 on 2021-05-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0052_auto_20210428_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote_ref',
            field=models.CharField(editable=False, max_length=10),
        ),
    ]
