# Generated by Django 3.1.8 on 2021-05-30 23:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0053_auto_20210524_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='overall_volume',
            field=models.CharField(blank=True, default=0, max_length=100, verbose_name='Volume Weight'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='overall_weight',
            field=models.CharField(blank=True, default=0, max_length=100, verbose_name='Actual Weight'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='volume_weight',
            field=models.CharField(blank=True, default=0, max_length=10, verbose_name='Volume Weight'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='volume_weight1',
            field=models.CharField(blank=True, default=0, max_length=10, verbose_name='Volume Weight'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='volume_weight2',
            field=models.CharField(blank=True, default=0, max_length=10, verbose_name='Volume Weight'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='volume_weight3',
            field=models.CharField(blank=True, default=0, max_length=10, verbose_name='Volume Weight'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='volume_weight4',
            field=models.CharField(blank=True, default=0, max_length=10, verbose_name='Volume Weight'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text="Max 30kg's", max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='weight1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text="Max 30kg's", max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='weight2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text="Max 30kg's", max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='weight3',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text="Max 30kg's", max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='weight4',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text="Max 30kg's", max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='overall_volume',
            field=models.CharField(blank=True, default=0, max_length=100, verbose_name='Volume Weight'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='overall_weight',
            field=models.CharField(blank=True, default=0, max_length=100, verbose_name='Actual Weight'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='volume_weight',
            field=models.CharField(blank=True, default=0, max_length=10, verbose_name='Volume Weight'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='volume_weight1',
            field=models.CharField(blank=True, default=0, max_length=10, verbose_name='Volume Weight'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='volume_weight2',
            field=models.CharField(blank=True, default=0, max_length=10, verbose_name='Volume Weight'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='volume_weight3',
            field=models.CharField(blank=True, default=0, max_length=10, verbose_name='Volume Weight'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='volume_weight4',
            field=models.CharField(blank=True, default=0, max_length=10, verbose_name='Volume Weight'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text="Max 30kg's", max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='quote',
            name='weight1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text="Max 30kg's", max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='weight2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text="Max 30kg's", max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='weight3',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text="Max 30kg's", max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='weight4',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text="Max 30kg's", max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='Weight'),
        ),
    ]
