# Generated by Django 3.1.8 on 2021-05-31 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0054_auto_20210530_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='height1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='height2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='height3',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='height4',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='length1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='length2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='length3',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='length4',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='width1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Width'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='width2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Width'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='width3',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Width'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='width4',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Width'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='quote',
            name='height1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='height2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='height3',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='height4',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='quote',
            name='length1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='length2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='length3',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='length4',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='quote',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='quote',
            name='width1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Width'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='width2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Width'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='width3',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Width'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='width4',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Width'),
        ),
    ]
