# Generated by Django 3.1.8 on 2021-05-31 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0055_auto_20210531_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='overall_volume',
            field=models.CharField(blank=True, default=0, max_length=12, verbose_name='Volume Weight'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='overall_weight',
            field=models.CharField(blank=True, default=0, max_length=12, verbose_name='Actual Weight'),
        ),
    ]
