# Generated by Django 3.1.8 on 2021-06-01 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0056_auto_20210531_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
