# Generated by Django 3.1.8 on 2021-06-02 13:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0057_auto_20210601_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='height1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='length1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='volume_weight1',
            field=models.CharField(blank=True, max_length=10, verbose_name='Volume Weight'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='weight1',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Max 30kg's", max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='width1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Width'),
        ),
    ]
