# Generated by Django 3.1.8 on 2021-06-03 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0060_auto_20210602_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='overall_volume',
            field=models.CharField(blank=True, default=0, max_length=120, verbose_name='Volume Weight'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='overall_weight',
            field=models.CharField(blank=True, default=0, max_length=120, verbose_name='Actual Weight'),
        ),
    ]
