# Generated by Django 3.1.4 on 2021-02-16 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='create_account',
            options={'verbose_name_plural': 'Create Account'},
        ),
    ]
