# Generated by Django 3.1.4 on 2021-02-16 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_account', '0003_auto_20210216_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_account',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='Complete'),
        ),
    ]
