# Generated by Django 3.1.4 on 2021-02-16 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_account', '0004_create_account_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_account',
            name='complete',
            field=models.BooleanField(default=False, help_text='Only Select Complete Once Account is 100% set up!', verbose_name='Complete'),
        ),
    ]
