# Generated by Django 3.1.4 on 2021-02-19 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_account', '0007_done_accounts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Done_accounts',
        ),
    ]
