# Generated by Django 3.1.8 on 2021-05-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_account', '0008_delete_done_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_account',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
