# Generated by Django 3.1.8 on 2021-05-13 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_cost',
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='collection_postcode',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='delivery_postcode',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='items',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
