# Generated by Django 3.1.8 on 2021-05-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20210513_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ten_percent_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
