# Generated by Django 3.1.8 on 2021-05-18 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_ten_percent_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='ten_percent_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='10% Discount'),
        ),
    ]
