# Generated by Django 3.1.8 on 2021-06-02 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_orderlineitem_chargable_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='jobs',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
