# Generated by Django 3.1.8 on 2021-06-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_order_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='jobs',
            field=models.IntegerField(null=True),
        ),
    ]
