# Generated by Django 3.1.4 on 2021-02-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faqs',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=254)),
                ('answer', models.TextField()),
                ('urls', models.URLField(blank=True, max_length=1024)),
            ],
        ),
    ]
