# Generated by Django 3.1.4 on 2021-02-09 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faqs',
            old_name='question_id',
            new_name='q_id',
        ),
    ]
