# Generated by Django 3.1.4 on 2021-02-09 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0002_auto_20210209_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faqs',
            old_name='question',
            new_name='questions',
        ),
    ]
