# Generated by Django 3.1.4 on 2021-02-09 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0003_auto_20210209_2242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faqs',
            old_name='questions',
            new_name='question',
        ),
    ]
