# Generated by Django 3.1.4 on 2021-02-15 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0004_auto_20210209_2243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqs',
            options={'verbose_name_plural': "FAQ's"},
        ),
    ]
