# Generated by Django 3.1.4 on 2021-01-05 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254)),
                ('category_type', models.CharField(blank=True, max_length=254)),
                ('description', models.TextField()),
                ('image1_url', models.URLField(blank=True, max_length=1024)),
                ('image1', models.ImageField(blank=True, upload_to='')),
                ('image2_url', models.URLField(blank=True, max_length=1024)),
                ('image2', models.ImageField(blank=True, upload_to='')),
                ('image3_url', models.URLField(blank=True, max_length=1024)),
                ('image3', models.ImageField(blank=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=254)),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('size', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('box_qty', models.IntegerField(blank=True, null=True)),
                ('per_roll', models.IntegerField(blank=True, null=True)),
                ('image1_url', models.URLField(blank=True, max_length=1024)),
                ('image1', models.ImageField(blank=True, upload_to='')),
                ('image2_url', models.URLField(blank=True, max_length=1024)),
                ('image2', models.ImageField(blank=True, upload_to='')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
            options={
                'ordering': ('category',),
            },
        ),
    ]
